on:
  push:
    branches:
      - 'main'
      - 'feature'
jobs:
  Terraform-job:
    name: terraform init
    runs-on: Ramrunner 
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        
    
