on:
  push:
    branches:
      - 'main'
      - 'feature'
jobs:
  Terraform-job:
    name: terraform init
    runs-on: Ramrunner 
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Install Terraform

        uses: little-core-labs/install-terraform@v2.0.0
        with:
          
          version: 1.13.0
      - name: Terraform init/plan
 
        uses: comu2e/tfnotify-composite-action@1.0.4
        with:
       
   
          
          
    
        
    
