name: github-pipeline1
on:
  push:
    branches:
      - main
      - feature/*

permissions:
  contents: read
  id-token: write

jobs:
  terraform-plan:
    runs-on: Ramrunner
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Azure Login
        uses: azure/login@v2.3.0
        with:
          client-id: e1dc23a5-f4d1-4d82-9d97-6d3bcee54fe1
          tenant-id: efeb520c-f48c-485c-95c5-be148c93599f
          subscription-id: c05900c4-9a99-417d-878e-413b907a6035

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./infra

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./infra/tfplan

  manual-approval:
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment: dev # <-- Ye environment approval ke liye
    steps:
      - name: Awaiting Approval
        run: echo "Waiting for approval..."

  terraform-apply:
    needs: manual-approval
    runs-on: Ramrunner
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Azure Login
        uses: azure/login@v2.3.0
        with:
          client-id: e1dc23a5-f4d1-4d82-9d97-6d3bcee54fe1
          tenant-id: efeb520c-f48c-485c-95c5-be148c93599f
          subscription-id: c05900c4-9a99-417d-878e-413b907a6035

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ./infra

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./infra
